-- H2 本地文件数据库初始化脚本。
-- base-0: EVOPS 初始工作区；algae-1: 微藻生物反应器培养与采收闭环。
CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('algae-1', '微藻培养与采收闭环：藻种批次/培养罐/培养批次/补液/采样/采收/审计');

-- 藻种批次（接种母批次）。strain_no 为关键业务键，必须唯一；验收后不得删除。
CREATE TABLE IF NOT EXISTS t_algae_strain (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strain_no       VARCHAR(64)  NOT NULL,
    strain_name     VARCHAR(128) NOT NULL,
    species         VARCHAR(128),
    source_org      VARCHAR(128),
    accepted        BOOLEAN      NOT NULL DEFAULT FALSE,
    accepted_date   DATE,
    accept_remark   VARCHAR(255),
    operator_code   VARCHAR(64)  NOT NULL DEFAULT 'unknown',
    version         INT          NOT NULL DEFAULT 0,
    create_by       BIGINT,
    create_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by       BIGINT,
    update_time     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_algae_strain_no UNIQUE (strain_no)
);

-- 培养罐（反应器柜位）。reactor_code 为关键业务键；柜位被在培养批次占用时不得删除。
CREATE TABLE IF NOT EXISTS t_algae_reactor (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reactor_code      VARCHAR(64)  NOT NULL,
    reactor_name      VARCHAR(128) NOT NULL,
    cabinet_position  VARCHAR(64)  NOT NULL,
    capacity_ml       DECIMAL(12,2) NOT NULL,
    status            VARCHAR(16)  NOT NULL DEFAULT 'AVAILABLE',
    operator_code     VARCHAR(64)  NOT NULL DEFAULT 'unknown',
    version           INT          NOT NULL DEFAULT 0,
    create_by         BIGINT,
    create_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_algae_reactor_code UNIQUE (reactor_code)
);

-- 培养批次。复合业务键 (batch_no, reactor_code) 必须唯一。
CREATE TABLE IF NOT EXISTS t_algae_culture_batch (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no             VARCHAR(64)  NOT NULL,
    reactor_code         VARCHAR(64)  NOT NULL,
    strain_no            VARCHAR(64)  NOT NULL,
    status               VARCHAR(16)  NOT NULL DEFAULT 'CREATED',
    initial_volume_ml    DECIMAL(12,2) NOT NULL,
    current_volume_ml    DECIMAL(12,2) NOT NULL,
    inoculation_date     DATE         NOT NULL,
    inoculation_timezone VARCHAR(64)  NOT NULL DEFAULT 'Asia/Shanghai',
    latest_ph            DECIMAL(6,3),
    latest_od            DECIMAL(8,4),
    latest_measure_date  DATE,
    operator_code        VARCHAR(64)  NOT NULL DEFAULT 'unknown',
    version              INT          NOT NULL DEFAULT 0,
    create_by            BIGINT,
    create_time          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by            BIGINT,
    update_time          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_algae_batch_reactor UNIQUE (batch_no, reactor_code)
);
CREATE INDEX IF NOT EXISTS idx_algae_batch_status ON t_algae_culture_batch (status);
CREATE INDEX IF NOT EXISTS idx_algae_batch_strain ON t_algae_culture_batch (strain_no);

-- 补液事件。feed_no 关键业务键唯一；落账（posted）后不得删除。
CREATE TABLE IF NOT EXISTS t_algae_feed_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    feed_no        VARCHAR(64)  NOT NULL,
    batch_id       BIGINT       NOT NULL,
    biz_date       DATE         NOT NULL,
    biz_timezone   VARCHAR(64)  NOT NULL DEFAULT 'Asia/Shanghai',
    medium         VARCHAR(128),
    feed_volume_ml DECIMAL(12,2) NOT NULL,
    ph_snapshot    DECIMAL(6,3) NOT NULL,
    od_snapshot    DECIMAL(8,4) NOT NULL,
    posted         BOOLEAN      NOT NULL DEFAULT FALSE,
    posted_at      TIMESTAMP,
    operator_code  VARCHAR(64)  NOT NULL DEFAULT 'unknown',
    version        INT          NOT NULL DEFAULT 0,
    create_by      BIGINT,
    create_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_algae_feed_no UNIQUE (feed_no)
);
CREATE INDEX IF NOT EXISTS idx_algae_feed_batch ON t_algae_feed_event (batch_id);
CREATE INDEX IF NOT EXISTS idx_algae_feed_bizdate ON t_algae_feed_event (biz_date);

-- 采样事件。sampling_no 关键业务键唯一；与批次 pH/OD 快照在同一事务写入。
CREATE TABLE IF NOT EXISTS t_algae_sampling_event (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sampling_no    VARCHAR(64)  NOT NULL,
    batch_id       BIGINT       NOT NULL,
    biz_date       DATE         NOT NULL,
    biz_timezone   VARCHAR(64)  NOT NULL DEFAULT 'Asia/Shanghai',
    sample_volume_ml DECIMAL(12,2),
    ph_snapshot    DECIMAL(6,3) NOT NULL,
    od_snapshot    DECIMAL(8,4) NOT NULL,
    remark         VARCHAR(255),
    operator_code  VARCHAR(64)  NOT NULL DEFAULT 'unknown',
    version        INT          NOT NULL DEFAULT 0,
    create_by      BIGINT,
    create_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by      BIGINT,
    update_time    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_algae_sampling_no UNIQUE (sampling_no)
);
CREATE INDEX IF NOT EXISTS idx_algae_sampling_batch ON t_algae_sampling_event (batch_id);
CREATE INDEX IF NOT EXISTS idx_algae_sampling_bizdate ON t_algae_sampling_event (biz_date);

-- 采收批次。harvest_no 关键业务键唯一；落账（posted）后不得删除。
CREATE TABLE IF NOT EXISTS t_algae_harvest_record (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    harvest_no        VARCHAR(64)  NOT NULL,
    batch_id          BIGINT       NOT NULL,
    biz_date          DATE         NOT NULL,
    biz_timezone      VARCHAR(64)  NOT NULL DEFAULT 'Asia/Shanghai',
    harvest_volume_ml DECIMAL(12,2) NOT NULL,
    ph_snapshot       DECIMAL(6,3) NOT NULL,
    od_snapshot       DECIMAL(8,4) NOT NULL,
    posted            BOOLEAN      NOT NULL DEFAULT FALSE,
    posted_at         TIMESTAMP,
    operator_code     VARCHAR(64)  NOT NULL DEFAULT 'unknown',
    version           INT          NOT NULL DEFAULT 0,
    create_by         BIGINT,
    create_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by         BIGINT,
    update_time       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_algae_harvest_no UNIQUE (harvest_no)
);
CREATE INDEX IF NOT EXISTS idx_algae_harvest_batch ON t_algae_harvest_record (batch_id);
CREATE INDEX IF NOT EXISTS idx_algae_harvest_bizdate ON t_algae_harvest_record (biz_date);

-- 业务审计日志：与跨表写入同事务提交，留存请求号、操作者、业务时区与版本快照。
CREATE TABLE IF NOT EXISTS t_algae_audit_log (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_no       VARCHAR(64)  NOT NULL,
    operator_code    VARCHAR(64)  NOT NULL,
    biz_timezone     VARCHAR(64)  NOT NULL,
    biz_object       VARCHAR(32)  NOT NULL,
    biz_action       VARCHAR(32)  NOT NULL,
    biz_keys         VARCHAR(255),
    biz_date         DATE,
    version_snapshot CLOB,
    create_by        BIGINT,
    create_time      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_by        BIGINT,
    update_time      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_algae_audit_request ON t_algae_audit_log (request_no);
